version: '2'

services:
  jupyter:
    container_name: cinc2017
    image: martinkropf/cinc2017
    working_dir: /notebooks
    ports:
      - "8888:8888"
    volumes:
      - /home/mk/ecg-classification/notebooks/:/notebooks
